# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4296c26f9895c6333fa08ce81c68b5238610c561e8cde51fffc8b511b75f55110bb03bc45d1f0ffb6fcb0f1c803b921f4e225a3abd17108dadb38bd74cad6e5

test:
  secret_key_base: 343e031093c26c9d8ceec37ad1c595ae312db6e2003272de93120053c6d668f0e80f38cd4676c26d4bef5b996099cf8367051b496e6252afd6ce319faaa8d8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
